version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.18
    steps:
      - checkout
      - run:
          name: "Go version in use:"
          command: |
            echo 'Is Go here?'
            go version
      - run:
          name: Running Unit tests
          command: |
            echo 'Running Unit tests...'
            go test -v
